export default [
    {
        avatar: require('../../assets/images/planets/Sun.png'),
        name: '太阳',
        engName: 'Sun',
        type: '黄矮星',
        radius: '约696,340千米',
        quality: '约为地球的33.3万倍',
        orbitLength: '约2.7万光年',
        rotationPeriod: '约25至36地球日',
        revolutionPeriod: '约225至250百万年',
        gravity: '约为地球的28倍',
        temperature: '约为5500摄氏度',
        intro: '太阳是太阳系的中心恒星，它通过核聚变将氢转变为氦，释放出巨大的能量和光辐射，供应太阳系中行星和其他天体所需的能量，是地球上生命最重要的能量来源。',
        component: '太阳主要由氢元素（约占质量的73.5%），和氦元素（约占质量的25%）组成，其余部分包括轻微的氧、碳、铁等元素',
    },
    {
        avatar: require('../../assets/images/planets/Mercury.png'),
        name: '水星',
        engName: 'Mercury',
        type: '岩石行星',
        radius: '约2,439千米',
        quality: '约为地球的0.3倍',
        orbitLength: '约为地球的0.4倍',
        rotationPeriod: '约58.6地球日',
        revolutionPeriod: '约88地球日',
        gravity: '约为地球的0.4倍',
        temperature: '白天 约427度\n晚上 约-173度',
        intro: '水星是太阳系中最小、最靠近太阳的行星。它是古罗马神话中的信使之神的名字。水星是第一个被观测到的太阳系内行星，并且在黎明和黄昏时经常被观察到。由于它靠近太阳，因此只能在黎明前或黄昏后的较低的天空位置看到它。',
        component: '水星主要由岩石和金属构成，这使得它被归类为岩质行星。它的岩石地壳包含硅酸盐岩石和一些较为稀有的金属元素，如铁、铝和镁。',
    },
    {
        avatar: require('../../assets/images/planets/Venus.png'),
        name: '金星',
        engName: 'Venus',
        type: '岩石行星',
        radius: '约6,051千米',
        quality: '约为地球的4.87倍',
        orbitLength: '约为地球的0.72倍',
        rotationPeriod: '约243地球日',
        revolutionPeriod: '约225地球日',
        gravity: '约为地球的0.9倍',
        temperature: '约465度',
        intro: '金星是太阳系中的第二颗行星，也被称为“晚星”或“晨星”，因为它的亮度使它在天空中看起来像一个明亮的点。金星是古罗马神话中爱与美的女神的名字。它是太阳系中体积和质量最接近地球的行星，但表面条件却截然不同。',
        component: '金星的表面主要由硅酸盐岩石构成，类似于地球的地壳组成。此外，金星的大气层主要由二氧化碳（约96%）组成，还有一些氮气和少量其他气体。这导致金星的厚重大气层形成了一个极端的温室效应，使其表面温度异常高。',
    },
    {
        avatar: require('../../assets/images/planets/Earth.png'),
        name: '地球',
        engName: 'Earth',
        type: '岩石行星',
        radius: '约6,371千米',
        quality: '约5.9×10^24千克',
        orbitLength: '约149.6百万千米',
        rotationPeriod: '1地球日',
        revolutionPeriod: '365地球日',
        gravity: '约为9.8米每平方秒(m/s²)',
        temperature: '平均约为15度',
        intro: '地球是我们生活的家园，也是目前已知宇宙中唯一已知存在生命的行星。它是太阳系中最大的岩石行星，同时也是第五颗最大的行星。地球是古代欧洲的盖亚神话所崇拜的母亲大地之神的名字',
        component: '地球的内部结构主要包含地核、外核、地幔和地壳。地核主要由铁和镍构成，地幔主要由硅、镁、铁等元素构成，地壳主要由硅酸盐岩石组成。地球的大气层主要由氮气（约78%）、氧气（约21%）、氩气和其他稀有气体组成，其中氧气对于地球上的生命至关重要',
    },
    {
        avatar: require('../../assets/images/planets/Mars.png'),
        name: '火星',
        engName: 'Mars',
        type: '岩石行星',
        radius: '约3,389千米',
        quality: '约为地球的0.6倍',
        orbitLength: '约为地球的1.5倍',
        rotationPeriod: '约24.7小时',
        revolutionPeriod: '约687地球日',
        gravity: '约为地球的0.4倍',
        temperature: '最高约为20度\n最低约为-153度',
        intro: '火星是太阳系中最接近地球的岩石行星之一，也是古罗马战争之神的名字。由于其表面呈现出红色，因此被称为“红色星球”。火星吸引了人类的关注，因为它是我们太阳系中最有希望进行人类登陆和探索的行星。',
        component: '火星的表面主要由硅酸盐岩石组成，类似于地球的地壳组成。火星的大气层主要由二氧化碳（约95%）、氮气（约3%）和少量其他气体组成。虽然火星的大气层相对较薄，但它的存在仍然对火星的气候和天气产生重要影响。',
    },
    {
        avatar: require('../../assets/images/planets/Jupiter.png'),
        name: '木星',
        engName: 'Jupiter',
        type: '气态行星',
        radius: '约69,911千米',
        quality: '约为地球的317.8倍',
        orbitLength: '约为地球的5.2倍',
        rotationPeriod: '约10小时',
        revolutionPeriod: '约为11.9地球年',
        gravity: '约为地球的2.5倍',
        temperature: '顶层温度约为-145度',
        intro: '木星是太阳系中最大的行星，也是古罗马主神之神的名字。它是一颗巨大的气态行星，质量约为地球的318倍，体积约为地球的1317倍。木星有一个明显的条纹状大气带，以及一个显著的“大红斑”气旋，是太阳系中最为著名的风暴之一。',
        component: '木星主要由氢（约占质量的75%）和氦（约占质量的24%）组成，类似于太阳的成分。此外，木星的大气层中还含有其他一些元素和化合物，如甲烷、水蒸气和氨等。它的内部结构包括一个由氢和氦构成的巨大气态外壳，以及一个可能包含岩石和冰的固体岩质核心。',
    },
    {
        avatar: require('../../assets/images/planets/Saturn.png'),
        name: '土星',
        engName: 'Saturn',
        type: '气态行星',
        radius: '约58,232千米',
        quality: '约为地球的95.2倍',
        orbitLength: '约为地球的9.5倍',
        rotationPeriod: '约10.5小时',
        revolutionPeriod: '约为29.5地球年',
        gravity: '约为地球的1.1倍',
        temperature: '顶层温度约为-180度',
        intro: '土星是太阳系中最大、最华丽的行星之一，也是古罗马农业之神的名字。它因其美丽的环系而闻名，这些环系由无数颗冰和岩石碎片组成，围绕着行星的赤道运行。土星的环系使其成为太阳系中最引人注目的行星之一',
        component: '土星主要由氢（约占质量的75%）和氦（约占质量的25%）组成，类似于太阳的成分。土星的大气层中还含有其他一些元素和化合物，如甲烷、氨和水等。它的内部结构包括一个由氢和氦构成的巨大气态外壳，以及一个可能包含岩石和冰的固体岩质核心',
    },
    {
        avatar: require('../../assets/images/planets/Uranus.png'),
        name: '天王星',
        engName: 'Uranus',
        type: '气态行星',
        radius: '约25,362千米',
        quality: '约为地球的14.5倍',
        orbitLength: '约为地球的19.2倍',
        rotationPeriod: '约17小时',
        revolutionPeriod: '约为84.01地球年',
        gravity: '约为地球的0.9倍',
        temperature: '顶层温度约为-224度',
        intro: '天王星是太阳系中最远离太阳的巨大气态行星，也是古罗马天空之神的名字。它以其特殊的倾斜自转轴而著称，这导致它的北极和南极在不同时间面对太阳，使其季节和天气独特且复杂',
        component: '天王星主要由氢（约占质量的83%）和氦（约占质量的15%）组成，类似于太阳的成分。除此之外，天王星的大气层中还含有其他一些元素和化合物，如甲烷、氨和水等。由于天王星的大气层相对较厚，其内部结构也可能包含岩石和冰的固体核心。',
    },
    {
        avatar: require('../../assets/images/planets/Neptune.png'),
        name: '海王星',
        engName: 'Neptune',
        type: '气态行星',
        radius: '约24,622千米',
        quality: '约为地球的17.1倍',
        orbitLength: '约为地球的30.1倍',
        rotationPeriod: '约为16小时',
        revolutionPeriod: '约为164.8地球年',
        gravity: '约为地球的1.2倍',
        temperature: '顶层温度约为-214度',
        intro: '海王星是太阳系中最遥远的行星之一，它是古罗马海洋之神的名字。由于它的遥远和暗淡，直到18世纪末才被天文学家发现。海王星以其深蓝色的外观和强大的风暴而著称，特别是它的大暗斑和高速风带',
        component: '海王星主要由氢（约占质量的80%）和氦（约占质量的19%）组成，类似于太阳的成分。除此之外，海王星的大气层中还含有其他一些元素和化合物，如甲烷、氨和水等。它的内部结构可能包含岩石和冰的固体核心，被称为“岩质冰核”',
    },
];
