import './zh-hans';

const { Blockly } = window;

// 这里仅为模板例子，需要自行重写

// block category color define
Blockly.Msg.VIRTUALHARDWARE_HEX_EVENTS = '#3eaedd';
Blockly.Msg.VIRTUALHARDWARE_HEX_CONTROL = '#a568f0';
Blockly.Msg.VIRTUALHARDWARE_HEX_MATH = '#f3ab3a';
Blockly.Msg.VIRTUALHARDWARE_HEX_VARIABLES = '#ff7f46';
Blockly.Msg.VIRTUALHARDWARE_HEX_FUNCTIONS = '#30ffd9';
Blockly.Msg.VIRTUALHARDWARE_HEX_ANIMATION = '#69c12e';
Blockly.Msg.VIRTUALHARDWARE_HEX_MOTION = '#d061bc';
Blockly.Msg.VIRTUALHARDWARE_HEX_SENSOR = '#ff6464';
Blockly.Msg.VIRTUALHARDWARE_HEX_AI = '#3eaedd';
Blockly.Msg.VIRTUALHARDWARE_HEX_EXTENSION = '#5b8bf8';
Blockly.Msg.VIRTUALHARDWARE_HEX_SENTENCE_RECOGNITION = '#a568f0';
Blockly.Msg.VIRTUALHARDWARE_HEX_AI_CHAT = '#d061bc';
Blockly.Msg.VIRTUALHARDWARE_HEX_TRANSLATE = '#ff6464';
Blockly.Msg.VIRTUALHARDWARE_HEX_TAKE_PHOTO = '#d061bc';
Blockly.Msg.VIRTUALHARDWARE_HEX_DETECT_PRODUCT_BETA = '#3eaedd';
Blockly.Msg.VIRTUALHARDWARE_HEX_ACTUATOR = '#d061bc';
Blockly.Msg.VIRTUALHARDWARE_HEX_SENSOR2 = '#3bd6ff';
Blockly.Msg.VIRTUALHARDWARE_HEX_POWER_DEVICE = '#a568f0';
Blockly.Msg.VIRTUALHARDWARE_HEX_PID = '#a568f0';
Blockly.Msg.VIRTUALHARDWARE_HEX_FREEBUILD_SENSOR = '#3bd6ff';
Blockly.Msg.VIRTUALHARDWARE_HEX_PLANET = '#d061bc';
Blockly.Msg.VIRTUALHARDWARE_HEX_TRICK = '#69c12e';
Blockly.Msg.VIRTUALHARDWARE_HEX_LIGHT = '#3eaedd';
Blockly.Msg.VIRTUALHARDWARE_HEX_TASK = '#3eaedd';
Blockly.Msg.VIRTUALHARDWARE_HEX_DATASET = '#a568f0';

Blockly.Msg.VAL_1 = '#fa8a57';
Blockly.Msg.VAL_2 = '#ff7f46';

// override default
Blockly.Msg.PROCEDURES_HUE = Blockly.Msg.VIRTUALHARDWARE_HEX_FUNCTIONS;
