export const EventMsg = {
  UPDATE_TABS: 'updateTabs',
  SHOW_TAB: 'showTab',
  STOP_RUNNING: 'stopRunning',
  SET_TASK_CONFIG: 'setTaskConfig',
  UPDATE_RUNNING_TIME: 'updateRunningTime',
  UPDATE_SCORE: 'updateScore',
  UPDATE_TASK_SCORE: 'updateTaskScore',
  ADD_SENSOR: 'addSensor',
  UPDATE_TAKE_PHOTO_BTN: 'updateTakePhotoBtn',
  UPDATE_DEVICES: 'updateDevices',
  UPDATE_PHOTO_DATA: 'updatePhotoData',
  UPDATE_ERROR_TIPS: 'updateErrorTips',
  UPDATE_COUNTDOWN: 'updateCountdown',
  UPDATE_COUNTDOWN_TIMER: 'updateCountdownTimer',
  UPDATE_STREAM_DATA: 'updateStreamData',
  RESET_VAR_AND_LIST: 'resetVarAndList',
  UPDATE_VAR_DATA: 'updateVarData',
  UPDATE_PID_VAR_DATA: 'updatePidVarData',
  UPDATE_LIST_DATA: 'updateListData',
  SYNC_AUDIO_SPECTROGRAM: 'syncAudioSpectrogram',
  SHOW_TM_AUDIO_PANEL: 'showTMAudioPanel',
  SET_EXERCISE_CONFIG: 'setExerciseConfig',
  HIDE_PAGE: 'hidePage',
  SHOW_PAGE: 'showPage',
  NOTIFY_PROJECT_CHANGED: 'notifyProjectChanged',
  NOTIFY_NOC_SAVE_PROJECT: 'notifyNocSaveProject',
  SET_NOC_URL: 'setNocUrl',
  IMPORT_PROJECT_RESULT: 'importProjectResult',
  GET_USER_ANSWER_RESULT: 'getUserAnswerResult',
  SHOW_DIALOG_RESULT: 'showDialogResult',
  WAIT_NOC_LOAD_SHOW_DIALOG_RESULT: 'waitNocLoadShowDialogResult',
  REQUIRE_SUBMIT_ONLINE_ANSWER_PAPER_RESULT: 'requireSubmitOnlineAnswerPaperResult',
  CHECK_IMPORT_RESULT: 'checkImportResult',
  UPDATE_ROBOT_TEXTURE: 'updateRobotTexture', // 更新机器人视图
  UPDATE_ROBOT_INFO: 'updateRobotInfo', // 更新机器人信息
  UPDATE_COMPETITION_TIME_CONFIG: 'updateCompetitionTimeConfig',
  GET_NOW_TIME_RESULT: 'getNowTimeResult',
  UPDATE_VIDEO_PROGRESS: 'updateVideoProgress',
  MOUSE_LEAVE_MULTI_PANELS: 'mouseLeaveMultiPanels',
  SWITCH_HOVER: 'switchHover',
};
